# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20, verbose_name='pvs ip address')),
                ('hardware', models.CharField(max_length=20, verbose_name='pi hardware')),
                ('revision', models.CharField(max_length=20, verbose_name='pi revision')),
                ('serial', models.CharField(max_length=20, verbose_name='pi serial')),
                ('dbconfig', models.TextField(default='{}', verbose_name='pvs dbconfig')),
                ('last_update_time', models.DateTimeField(verbose_name='last update time')),
            ],
        ),
    ]
