# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 12:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='hardware',
            field=models.CharField(default='', max_length=20, verbose_name='pi hardware'),
        ),
        migrations.AlterField(
            model_name='report',
            name='ip',
            field=models.CharField(default='', max_length=20, verbose_name='pvs ip address'),
        ),
        migrations.AlterField(
            model_name='report',
            name='last_update_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='last update time'),
        ),
        migrations.AlterField(
            model_name='report',
            name='revision',
            field=models.CharField(default='', max_length=20, verbose_name='pi revision'),
        ),
        migrations.AlterField(
            model_name='report',
            name='serial',
            field=models.CharField(default='', max_length=20, verbose_name='pi serial'),
        ),
    ]
