# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvs', '0003_dbconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Energy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=20, verbose_name='pi serial')),
                ('client_id', models.IntegerField(null=True, verbose_name='rowdata id in pvs')),
                ('create_time', models.DateTimeField(verbose_name='pvi energy read time')),
                ('pvi_name', models.CharField(max_length=50, null=True, verbose_name='pvi name in pvs')),
                ('modbus_id', models.IntegerField(verbose_name='modbus id the value from')),
                ('value', models.IntegerField(verbose_name='pvi energy value')),
                ('type', models.CharField(choices=[('en_dc_life', 'Energy Output DC Life'), ('en_today', 'Energy Output Today'), ('ac_v', 'AC Output Voltage'), ('ac_c', 'AC Output Current'), ('ac_w', 'AC Output Watt')], max_length=20, verbose_name='energy vaule type')),
                ('measure_index', models.CharField(choices=[('dc1', 'dc1'), ('dc2', 'dc2'), ('dc3', 'dc3')], default='dc1', max_length=10, null=True, verbose_name='pvi measure index')),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=20, verbose_name='pi serial')),
                ('create_time', models.DateTimeField(verbose_name='pvs environment weather read time')),
                ('temperature', models.FloatField(null=True, verbose_name='temperature value at site')),
                ('uv', models.IntegerField(null=True, verbose_name='UV index at site')),
                ('visibility', models.FloatField(null=True, verbose_name='visibility Index at site')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='local_ip',
            field=models.CharField(max_length=20, null=True, verbose_name='pvs local ip address'),
        ),
    ]
