# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvs', '0004_auto_20160926_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='energy',
            old_name='client_id',
            new_name='data_id',
        ),
        migrations.RemoveField(
            model_name='energy',
            name='measure_index',
        ),
        migrations.AddField(
            model_name='energy',
            name='measurement_index',
            field=models.CharField(choices=[('dc1', 'dc1'), ('dc2', 'dc2'), ('dc3', 'dc3')], default='dc1', max_length=10, null=True, verbose_name='pvi measurement index'),
        ),
        migrations.AlterField(
            model_name='energy',
            name='type',
            field=models.CharField(choices=[('en_dc_life', 'Energy Output DC Life'), ('en_today', 'Energy Output Today'), ('ac_v', 'AC Output Voltage'), ('ac_c', 'AC Output Current'), ('ac_w', 'AC Output Watt')], max_length=20, verbose_name='energy value type'),
        ),
    ]
